/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AcmeAccordion {
        "headerText": string;
    }
    interface AcmeProductCard {
        "badge": string;
        "desc": string;
        "imageSrc": string;
        "name": string;
        "pid": string;
        "price": number;
    }
}
declare global {
    interface HTMLAcmeAccordionElement extends Components.AcmeAccordion, HTMLStencilElement {
    }
    var HTMLAcmeAccordionElement: {
        prototype: HTMLAcmeAccordionElement;
        new (): HTMLAcmeAccordionElement;
    };
    interface HTMLAcmeProductCardElement extends Components.AcmeProductCard, HTMLStencilElement {
    }
    var HTMLAcmeProductCardElement: {
        prototype: HTMLAcmeProductCardElement;
        new (): HTMLAcmeProductCardElement;
    };
    interface HTMLElementTagNameMap {
        "acme-accordion": HTMLAcmeAccordionElement;
        "acme-product-card": HTMLAcmeProductCardElement;
    }
}
declare namespace LocalJSX {
    interface AcmeAccordion {
        "headerText"?: string;
    }
    interface AcmeProductCard {
        "badge"?: string;
        "desc"?: string;
        "imageSrc"?: string;
        "name"?: string;
        "onAddToCart"?: (event: CustomEvent<string>) => void;
        "pid"?: string;
        "price"?: number;
    }
    interface IntrinsicElements {
        "acme-accordion": AcmeAccordion;
        "acme-product-card": AcmeProductCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "acme-accordion": LocalJSX.AcmeAccordion & JSXBase.HTMLAttributes<HTMLAcmeAccordionElement>;
            "acme-product-card": LocalJSX.AcmeProductCard & JSXBase.HTMLAttributes<HTMLAcmeProductCardElement>;
        }
    }
}
